
package ch.furthermore.poc.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StringUtils", targetNamespace = "http://poc.furthermore.ch/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StringUtils {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "upperCase", targetNamespace = "http://poc.furthermore.ch/", className = "ch.furthermore.poc.client.UpperCase")
    @ResponseWrapper(localName = "upperCaseResponse", targetNamespace = "http://poc.furthermore.ch/", className = "ch.furthermore.poc.client.UpperCaseResponse")
    public String upperCase(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
