package ch.furthermore.poc;

import java.net.MalformedURLException;

import javax.xml.ws.BindingProvider;

import ch.furthermore.poc.client.StringUtils;
import ch.furthermore.poc.client.StringUtilsService;

/**
 * Run sample:
 * <pre>
 * mvn clean install
 * java -cp target/wildfly-swarm-jaxws-sample-client-0.0.1-SNAPSHOT.jar ch.furthermore.poc.Demo
 * </pre>
 */
public class Demo {
	public static void main(String[] args) throws MalformedURLException {
		//Below: Avoid online run-time access to WSDL (http://localhost:8080/StringUtils?wsdl)
		//		 src/main/resources/ch/furthermore/poc/upper.wsdl downloaded from http://localhost:8080/StringUtils?wsdl at design-time
		//       StringUtilsService.class class was generated by the JAX-WS RI 2.2 tools (from WSDL)
		StringUtilsService service = new StringUtilsService(Demo.class.getResource("upper.wsdl"));
		
//		StringUtilsService service = new StringUtilsService(new URL("http://localhost:8080/StringUtils?wsdl"));
//		StringUtilsService service = new StringUtilsService(new URL("https://httpecho-167219.appspot.com/soap/upper.wsdl")); 
		
		StringUtils port = service.getStringUtilsPort();
		
		//Below: Adjust "soap:address location" in WSDL to different endpoint
		BindingProvider bp = (BindingProvider)port;
		bp.getRequestContext().put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, "https://httpecho-167219.appspot.com/soap/upper");
		
		System.out.println(port.upperCase("Hello World"));
	}
}
